### ISSUE TITLE
Requirements to run the script

### ISSUE THREAD

**Issue by ethahtz** [qizhust/esceme#1]
Hi, I saw that a lot of python code referred to files in the dataset directory, but it is currently empty from the repository. Are there links shared to get those files necessary to run the scripts? And if possible, do you have a brief description of how to run the pre-training of esceme-enhanced models? Thank you!

**Comment by qizhust** [comment]
Thank you for your question. The datasets directory is indeed meant to house the data, not the Python code. You can access the necessary data via this [link](https://www.dropbox.com/sh/3a5j03u286px604/AABNp887W7_Fhgv13gUt4wzda?dl=0), which is shared through the [HAMT repository](https://github.com/cshizhe/VLN-HAMT).

As for the pre-training of esceme-enhanced models, it's important to note that there is no additional pre-training required. The results of Esceme* are obtained through a two-step inference process.

**Comment by GalaxyS1ayer** [comment]
Hi, I saw a lot of visualization results of navigation steps in your paper, could you tell me how to get these results?
